modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
issueTrackerURL="https://github.com/ChiefArug/ManaStorm-Reactor/issues" #optional

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="pack.png" #optional
#credits="" #optional
authors="${mod_authors}" #optional

displayTest="IGNORE_SERVER_VERSION"

# The description text for the mod (multi line!) (#mandatory)
description='''${mod_description}'''

[[dependencies."${mod_id}"]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="botania"
    mandatory=true
    versionRange="${botania_range}"
    ordering="NONE"
    side="BOTH"
